In [1]:
import torch

In [2]:
x=torch.Tensor(3,4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [3]:
type(x)

torch.Tensor

In [4]:
x=torch.Tensor(3,4,2)

In [5]:
print(x)

tensor([[[7.2149e+22, 1.9346e-19],
         [1.6045e+02, 1.0485e+21],
         [7.9050e+31, 4.2964e+24],
         [6.4099e-10, 6.4097e-10]],

        [[6.4097e-10, 4.4659e+33],
         [2.6509e+17, 1.1289e+27],
         [7.1420e+31, 1.7464e+31],
         [1.3774e+01, 2.6841e+17]],

        [[1.7484e+25, 4.5448e+30],
         [1.2271e+01, 2.9759e+29],
         [2.6703e-06, 6.1114e-04],
         [1.2703e+25, 1.1562e+19]]])


In [6]:
x=torch.DoubleTensor(3,4,2)

In [7]:
print(x)

tensor([[[7.4923e+247, 5.0203e+175],
         [ 1.8315e-76, 3.8376e+175],
         [4.0116e+174, 8.8310e+169],
         [ 1.6730e-76,  4.2622e-96]],

        [[1.1286e+277, 8.9317e+271],
         [7.3372e+223, 1.7010e+256],
         [5.4911e-143, 1.0640e+224],
         [3.9604e+246,  1.1632e-28]],

        [[ 1.7235e-47,  2.3378e-52],
         [9.5826e+169,  1.8699e-51],
         [2.2415e+174,  3.3616e-67],
         [ 8.2644e-72,  3.0545e-28]]], dtype=torch.float64)


In [8]:
x=torch.LongTensor(3,4,2)
print(x)

tensor([[[7219332012492535094, 7149295506217526073],
         [3473224411978610022, 3180160578315760432],
         [8751724873810518560, 8675377779008759152],
         [7310010034525922149, 8440344025574763632]],

        [[2478507435169572211, 7958535038077902906],
         [8296228837497597281, 4189032028197581669],
         [3907207156804821536, 3834362510814557026],
         [7149856041691723833, 3847872021226742372]],

        [[7215364926925399347, 3612485285161825377],
         [3543545863331918384, 4194877902962119734],
         [3545802087011857458, 7311068566657325619],
         [2322206415573840754,     137585841026338]]])


In [9]:
x=torch.IntTensor(3,4,2)
print(x)

tensor([[[1702130537,  543450482],
         [1126200417, 1650678842],
         [1954115676, 1751347823],
         [ 808464735,  808464432]],

        [[ 808464432, 2002530352],
         [1550545519, 1818850658],
         [1952537700, 1935437413],
         [1096573810, 1550738772]],

        [[1768383826, 1919251571],
         [1094997315, 1886413614],
         [ 909325370,  975189299],
         [1764237370, 1595962478]]], dtype=torch.int32)


In [10]:
list=[[1,2,3],[4,5,6],[7,8,9]]

In [11]:
x=torch.Tensor(list)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [12]:
x=torch.Tensor([[4,5,6],[7,8,9]])
print(x)

tensor([[4., 5., 6.],
        [7., 8., 9.]])


In [13]:
print(x[0][1])

tensor(5.)


In [14]:
print(x[1][2])

tensor(9.)


In [15]:
x[1][2]=10

In [16]:
print(x)

tensor([[ 4.,  5.,  6.],
        [ 7.,  8., 10.]])


In [17]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
torch.rand(2,4)

tensor([[0.8627, 0.3517, 0.9125, 0.5640],
        [0.1458, 0.0224, 0.2492, 0.3320]])

In [20]:
a=torch.Tensor([1,2,3])
b=torch.Tensor([6,8,9])
torch.dot(a,b)

tensor(49.)

In [21]:
a=torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
b=torch.Tensor([6,8,9])
torch.mv(a,b)

tensor([ 49., 118., 187.])

In [22]:
b=torch.Tensor([[4,5,6],[6,8,9],[1,2,3]])
torch.mm(a,b)

tensor([[ 19.,  27.,  33.],
        [ 52.,  72.,  87.],
        [ 85., 117., 141.]])

In [24]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [26]:
c=torch.mm(a,b)

In [27]:
c

tensor([[ 19.,  27.,  33.],
        [ 52.,  72.,  87.],
        [ 85., 117., 141.]])

In [28]:
torch.cat((a,c),0)

tensor([[  1.,   2.,   3.],
        [  4.,   5.,   6.],
        [  7.,   8.,   9.],
        [ 19.,  27.,  33.],
        [ 52.,  72.,  87.],
        [ 85., 117., 141.]])

In [29]:
torch.cat((a,c),1)

tensor([[  1.,   2.,   3.,  19.,  27.,  33.],
        [  4.,   5.,   6.,  52.,  72.,  87.],
        [  7.,   8.,   9.,  85., 117., 141.]])

In [30]:
d=torch.cat((a,c),1)

In [31]:
torch.chunk(d,2,1)

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([[ 19.,  27.,  33.],
         [ 52.,  72.,  87.],
         [ 85., 117., 141.]]))

In [32]:
torch.chunk(d,3,1)

(tensor([[1., 2.],
         [4., 5.],
         [7., 8.]]),
 tensor([[ 3., 19.],
         [ 6., 52.],
         [ 9., 85.]]),
 tensor([[ 27.,  33.],
         [ 72.,  87.],
         [117., 141.]]))

In [33]:
torch.chunk(d,2,0)

(tensor([[ 1.,  2.,  3., 19., 27., 33.],
         [ 4.,  5.,  6., 52., 72., 87.]]),
 tensor([[  7.,   8.,   9.,  85., 117., 141.]]))

In [34]:
m,n=torch.chunk(d,2,1)

In [35]:
m

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [36]:
n

tensor([[ 19.,  27.,  33.],
        [ 52.,  72.,  87.],
        [ 85., 117., 141.]])

In [38]:
torch.cuda.is_available()

True